Tests/coverage plugin integrations tests for review
jenkinsci/code-coverage-api-plugin pull request #268
Opened 2021-12-03 20:08 UTC by Tjuri

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-12-04 21:44 UTC, uhafner commented
Here is a patch for your delta computation:
https://github.com/jenkinsci/code-coverage-api-plugin/commit/4f881723efad6fd313b25b042088aa6e520d74f0

2021-12-04 21:55 UTC, uhafner commented on src/test/java/io/jenkins/plugins/coverage/model/CoveragePluginPipelineITest.java
> +        Run<?, ?> secondBuild = createPipelineJobAndAssertBuildResult(
This creates another job. However it must be the second build of the same job!

2021-12-04 22:05 UTC, uhafner commented on src/test/java/io/jenkins/plugins/coverage/model/CoveragePluginPipelineITest.java
> +                        + "   publishCoverage adapters: [jacocoAdapter(path: '*.xml')], sourceFileResolver: sourceFiles('NEVER_STORE')"
Here you need to call

```

```

2021-12-04 22:07 UTC, uhafner reviewed
It is hard to make a review here when almost every line contains a warning. Please check the coding style.

2021-12-05 14:53 UTC, uhafner requested changes

2021-12-05 14:53 UTC, uhafner commented on src/test/java/io/jenkins/plugins/coverage/model/CoveragePluginFreestyleITest.java
> +        assertThat(build.getResult()).isEqualTo(Result.FAILURE);
This is already included in line 207

2021-12-05 14:53 UTC, uhafner commented on src/test/java/io/jenkins/plugins/coverage/model/CoveragePluginFreestyleITest.java
> +        Run<?, ?> build = buildWithResult(project, Result.SUCCESS);
DRY!

Try to use one method with parameters.

2021-12-05 14:53 UTC, uhafner commented on src/test/java/io/jenkins/plugins/coverage/model/CoveragePluginFreestyleITest.java
> +                .contains("[Checks API] No suitable checks publisher found.");
See above: almost the same code

2021-12-05 14:53 UTC, uhafner commented on src/test/java/io/jenkins/plugins/coverage/model/CoveragePluginPipelineITest.java
> +    }
Here assertions are missing that check for the source code.

2021-12-09 21:48 UTC, NikolasFunction commented
Unfortunately, we couldn't achieve a green tick here. Thus, a few notes about our work here:

- Some integration tests revealed bugs in the source code. These tests are ignored using `@Ignore`
- Integration test `pipelineWithDockerAgent` currently fails when executed on a windows machine during the pipeline. We couldn't find any reason why.
- Static code analysis notices a few issues. We could not avoid them due to the following reason(s):
  - Methods throw Exceptions because inside, a used method throws `Exception` explicitly
  - Unused imports are actually used, but not in the working code itself but in the javadoc. Is this a bug in static code analysis?
  - `JavaGitContainer` is not our responsibility

2022-02-11 12:05 UTC, uhafner approved these changes
Thank you very much for these tests! Since we can merge only of these similar pull requests of our assignment I am closing this one now.

2022-02-11 12:06 UTC, closed without merging